name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"

# Emoji reference: https://gitmoji.carloscuesta.me/
categories:
  - title: 💥 Breaking changes
    label: breaking
  - title: 📋 Markdown Templates
    label: templates
  - title: ⚙️ Reusable Workflows
    label: workflows
  - title: 🛠️ Actions
    label: actions
  - title: 🔧 Maintenance
    label: maintenance
  - title: 📚 Documentation
    label: documentation
  - title: ✍ Other changes

change-template: "- $TITLE (#$NUMBER)"
version-resolver:
  major:
    labels:
      - "bump-major"
  minor:
    labels:
      - "bump-minor"
  default: patch
template: |
  ## What's Changed

  $CHANGES

exclude-labels:
  - "skip-release-notes"
